# Generated by Django 2.2.6 on 2021-05-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210519_1708'),
        ('posts', '0004_post_title'),
    ]

    operations = [
    ]
