# Generated by Django 2.2.6 on 2021-05-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210516_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, help_text='Заголовок', max_length=200, null=True, verbose_name='Заголовок сообщения'),
        ),
    ]
